apiVersion: v1
kind: Secret
metadata:
  name: article-extractor-secret
  namespace: jhon-silva-38
  labels:
    app: article-summarizer
    component: secret
type: Opaque
data:
  # Datos SENSIBLES únicamente (Base64 encoded)
  # Para generar: echo -n "valor" | base64

  # Database Password
  DATABASE_PASSWORD: bnBnX3BIVDROSngzZ25TRw==
  # Decodifica a: npg_pHT4NJx3gnSG

  # RapidAPI Key
  RAPIDAPI_KEY: MTEyZjk5ZTJjM21zaDdjMTUxNmQ0NmQ0MGU1ZXAxY2Y1ODBqc25lNGIxNGZmMTJmOGY=
  # Decodifica a: 112f99e2c3msh7c1516d46d40e5ep1cf580jsne4b14ff12f8f
