apiVersion: v1
kind: Secret
metadata:
  name: jhon-silva-38-secret
  namespace: jhon-silva-38
  labels:
    app: article-summarizer
    name: jhon-silva-38-secret
type: Opaque
data:
  # Base64 encoded values
  DATABASE_URL: cjJkYmM6cG9zdGdyZXNxbDovL2VwLXJvdWdoLXZpb2xldC1hZGk2cmkway1wb29sZXIuYy0yLnVzLWVhc3QtMS5hd3MubmVvbi50ZWNoL2lhX2FydGljbGVfZXh0cmFjdG9yP3NzbG1vZGU9cmVxdWlyZSZjaGFubmVsX2JpbmRpbmc9cmVxdWlyZQ==
  DATABASE_USERNAME: bmVvbmRiX293bmVy
  DATABASE_PASSWORD: bnBnX3BIVDROSngzZ25TRw==
  RAPIDAPI_KEY: MTEwMWUwZGE0ZG1zaDY3ZTVjMDRmNjM5NjUyYnAxNDUyYTRqc243NzY3YTUyMDkyZGM=
  RAPIDAPI_HOST: YXJ0aWNsZS1leHRyYWN0b3ItYW5kLXN1bW1hcml6ZXIucC5yYXBpZGFwaS5jb20=
  RAPIDAPI_BASE_URL: aHR0cHM6Ly9hcnRpY2xlLWV4dHJhY3Rvci1hbmQtc3VtbWFyaXplci5wLnJhcGlkYXBpLmNvbQ==
