apiVersion: v1
kind: Service
metadata:
  name: jhon-silva-38-service
  namespace: jhon-silva-38
  labels:
    app: article-summarizer
    name: jhon-silva-38-service
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    app: article-summarizer
    name: jhon-silva-38-deployment
