apiVersion: v1
kind: Secret
metadata:
  name: jhon-silva-38-secret
  namespace: jhon-silva-38
type: Opaque
data:
  # Base64 encoded values
  MONGO_DATABASE: aWFDYXJ0b24=  # iaCarton
  MONGO_URI: bW9uZ29kYitzcnY6Ly9qaG9uc2lsdmFsYXVyYV9maXRHeW06amhvbmJyYXluc2lsdmFAZml0Z3ltLjYxcmRpbXYubW9uZ29kYi5uZXQvP2FwcE5hbWU9Rml0R3lt  # mongodb+srv://jhonsilvalaura_fitGym:jhonbrayansilva@fitgym.61rdimv.mongodb.net/?appName=FitGym
  RAPIDAPI_KEY: MTEwMWUwZGE0ZG1zaDY3ZTVjMDRmNjM5NjUyYnAxNDUyYTRqc243NzY3YTUyMDkyZGM=  # 1101e0da4dmsh67e5c04f639652bp1452a4jsn7767a52092dc
  RAPIDAPI_HOST: YWktY2FydG9vbi1nZW5lcmF0b3IucC5yYXBpZGFwaS5jb20=  # ai-cartoon-generator.p.rapidapi.com
  RAPIDAPI_BASE_URL: aHR0cHM6Ly9haS1jYXJ0b29uLWdlbmVyYXRvci5wLnJhcGlkYXBpLmNvbQ==  # https://ai-cartoon-generator.p.rapidapi.com
