apiVersion: apps/v1
kind: Deployment
metadata:
  name: jhon-silva-38-deployment
  namespace: jhon-silva-38
  labels:
    app: jhon-silva-38-cartoon
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jhon-silva-38-cartoon
  template:
    metadata:
      labels:
        app: jhon-silva-38-cartoon
        version: v1
    spec:
      containers:
      - name: cartoon-api
        image: jhonbrayansilvalaura/cartoon-generator:latest
        ports:
        - containerPort: 8085
          protocol: TCP
        env:
        - name: MONGO_DATABASE
          valueFrom:
            secretKeyRef:
              name: jhon-silva-38-secret
              key: MONGO_DATABASE
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: jhon-silva-38-secret
              key: MONGO_URI
        - name: RAPIDAPI_KEY
          valueFrom:
            secretKeyRef:
              name: jhon-silva-38-secret
              key: RAPIDAPI_KEY
        - name: RAPIDAPI_HOST
          valueFrom:
            secretKeyRef:
              name: jhon-silva-38-secret
              key: RAPIDAPI_HOST
        - name: RAPIDAPI_BASE_URL
          valueFrom:
            secretKeyRef:
              name: jhon-silva-38-secret
              key: RAPIDAPI_BASE_URL
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /swagger-ui.html
            port: 8085
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /swagger-ui.html
            port: 8085
          initialDelaySeconds: 30
          periodSeconds: 10
      restartPolicy: Always
